CREATE TABLE IF NOT EXISTS transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    amount DOUBLE NOT NULL,
    category VARCHAR(50) NOT NULL,
    date VARCHAR(20) NOT NULL
);

ALTER TABLE transactions
MODIFY COLUMN id INT AUTO_INCREMENT;